# Generated by Django 4.1.5 on 2023-03-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_project_dataset_project_features_project_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='algorithm',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
