# Generated by Django 4.1.5 on 2023-03-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_user_avatar_remove_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
